# Generated by Django 4.1.7 on 2023-07-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chains", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.CharField(max_length=256)),
                ("words", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Word",
        ),
    ]
